function [ shape_Matrix ] = get_shapeMat(a, b, c, theta, phi, psi )
%caculate the shape Matrix based on the given 6 parameters
axis_Matrix = [1/a^2, 0, 0; 0, 1/b^2, 0; 0, 0, 1/c^2];

Rotation_Matrix = [cos(theta) * cos(phi) * cos(psi) - sin(phi) * sin(psi),...
                   cos(theta) * sin(phi) * cos(psi) + cos(phi) * sin(psi),...
                   -sin(theta) *cos(psi);...
                   -cos(theta) * cos(phi) * sin(psi) - sin(phi) * cos(psi),...
                   -cos(theta) * sin(phi) * sin(psi) + cos(phi) * cos(psi),...
                   sin(theta) * sin(psi);...
                   sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta)];

shape_Matrix = Rotation_Matrix * axis_Matrix * Rotation_Matrix';

end

